-- Supabase / PostgreSQL Database Schema
-- Multi-Tenant (SaaS) Architecture

-- 1. Agencies (Tenants)
CREATE TABLE agencies (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(150) NOT NULL,
  contact_email varchar(100) DEFAULT NULL,
  phone varchar(15) DEFAULT NULL,
  status varchar(20) CHECK (status IN ('ACTIVE','INACTIVE')) DEFAULT 'ACTIVE',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- 2. Users
CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  name varchar(100) NOT NULL,
  email varchar(100) DEFAULT NULL UNIQUE,
  phone varchar(15) DEFAULT NULL UNIQUE,
  password varchar(255) DEFAULT NULL,
  role varchar(50) CHECK (role IN ('OWNER','DRIVER','CASHIER','GODOWN_MANAGER','PURCHASE_MANAGER','SUPPORT','CUSTOMER')) DEFAULT NULL,
  aadhaar_number varchar(20) DEFAULT NULL,
  bank_account_holder_name varchar(150) DEFAULT NULL,
  bank_name varchar(150) DEFAULT NULL,
  bank_account_number varchar(50) DEFAULT NULL,
  bank_ifsc_code varchar(20) DEFAULT NULL,
  status varchar(20) CHECK (status IN ('ACTIVE','INACTIVE')) DEFAULT 'ACTIVE',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_job_profiles (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  user_id integer NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  display_role varchar(50) CHECK (display_role IN ('GODOWN_MANAGER','PURCHASE_DRIVER','DELIVERY_AGENT','CASHIER','CUSTOMER_SERVICE','MANAGER')) NOT NULL,
  age integer DEFAULT NULL,
  date_of_birth date DEFAULT NULL,
  gender varchar(20) CHECK (gender IN ('MALE','FEMALE','OTHER')) DEFAULT NULL,
  address text,
  vehicle_number varchar(60) DEFAULT NULL,
  vehicle_type varchar(60) DEFAULT NULL,
  driving_license_number varchar(120) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  name varchar(100) NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (agency_id, name)
);

CREATE TABLE stock_areas (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  name varchar(100) NOT NULL,
  address varchar(255) NOT NULL,
  manager_id integer REFERENCES users (id) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (agency_id, name)
);

CREATE TABLE drivers (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  user_id integer UNIQUE REFERENCES users (id) ON DELETE CASCADE DEFAULT NULL,
  vehicle_number varchar(50) DEFAULT NULL,
  license_number varchar(100) DEFAULT NULL,
  is_available boolean DEFAULT true,
  rating decimal(2,1) DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE addresses (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  user_id integer REFERENCES users (id) ON DELETE CASCADE DEFAULT NULL,
  address text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE expenses (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  category varchar(100) DEFAULT NULL,
  description text,
  amount decimal(10,2) DEFAULT NULL,
  bill_url text,
  created_by integer REFERENCES users (id) DEFAULT NULL,
  status varchar(20) CHECK (status IN ('PENDING','APPROVED','REJECTED')) DEFAULT 'PENDING',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_trips (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  purchase_manager_id integer NOT NULL REFERENCES users (id),
  stock_area_id integer REFERENCES stock_areas (id) ON DELETE SET NULL DEFAULT NULL,
  odometer_reading integer NOT NULL,
  end_odometer_reading integer DEFAULT NULL,
  odometer_image_url text,
  end_odometer_image_url text,
  status varchar(50) CHECK (status IN ('IN_PROGRESS','WAITING_APPROVAL','APPROVED','COMPLETED','CANCELLED')) NOT NULL DEFAULT 'IN_PROGRESS',
  started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  ended_at timestamp with time zone DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_loads (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  trip_id integer NOT NULL REFERENCES purchase_trips (id) ON DELETE CASCADE,
  created_by integer NOT NULL REFERENCES users (id),
  stock_area_id integer REFERENCES stock_areas (id) ON DELETE SET NULL DEFAULT NULL,
  product_type varchar(50) CHECK (product_type IN ('DOMESTIC','COMMERCIAL','MIXED')) NOT NULL,
  invoice_url text,
  invoice_source varchar(50) CHECK (invoice_source IN ('CAMERA','GALLERY')) DEFAULT NULL,
  total_quantity integer NOT NULL DEFAULT 0,
  status varchar(50) CHECK (status IN ('DRAFT','PENDING','APPROVED','CANCELLED')) NOT NULL DEFAULT 'DRAFT',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  name varchar(100) DEFAULT NULL,
  type varchar(50) CHECK (type IN ('DOMESTIC','COMMERCIAL')) DEFAULT NULL,
  category_id integer REFERENCES categories (id) DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  user_id integer UNIQUE REFERENCES users (id) ON DELETE SET NULL,
  consumer_number varchar(100) DEFAULT NULL,
  name varchar(150) NOT NULL,
  address text,
  phone varchar(15) DEFAULT NULL,
  connection_category varchar(50) DEFAULT NULL,
  default_product_id integer REFERENCES products (id) ON DELETE SET NULL,
  status varchar(20) CHECK (status IN ('ACTIVE','INACTIVE')) DEFAULT 'ACTIVE',
  delivery_charge decimal(10,2) DEFAULT 0.00,
  cylinders_in_hand integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_load_items (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  load_id integer NOT NULL REFERENCES purchase_loads (id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products (id),
  quantity integer NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reports (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  report_type varchar(100) DEFAULT NULL,
  generated_by integer REFERENCES users (id) DEFAULT NULL,
  file_url text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE issues (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  customer_id integer REFERENCES customers (id) ON DELETE CASCADE DEFAULT NULL,
  title varchar(255) DEFAULT NULL,
  description text,
  priority varchar(20) CHECK (priority IN ('LOW','MEDIUM','HIGH')) DEFAULT NULL,
  status varchar(50) CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED')) DEFAULT NULL,
  assigned_to integer REFERENCES users (id) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cash_collections (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  driver_id integer REFERENCES drivers (id) DEFAULT NULL,
  total_collected decimal(10,2) DEFAULT NULL,
  collection_date date DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE settlements (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  driver_id integer REFERENCES drivers (id) DEFAULT NULL,
  amount decimal(10,2) DEFAULT NULL,
  status varchar(50) CHECK (status IN ('SETTLED','PARTIAL','PENDING')) DEFAULT NULL,
  settlement_date date DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (driver_id, settlement_date)
);

CREATE TABLE stock (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  product_id integer DEFAULT NULL,
  stock_area_id integer REFERENCES stock_areas (id) DEFAULT NULL,
  quantity integer DEFAULT 0,
  quantity_return integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  empty_quantity integer DEFAULT NULL,
  defective_quantity integer DEFAULT NULL,
  system_quantity integer NOT NULL DEFAULT 0,
  UNIQUE (product_id, stock_area_id)
);

CREATE TABLE stock_transactions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  product_id integer REFERENCES products (id) DEFAULT NULL,
  stock_area_id integer REFERENCES stock_areas (id) DEFAULT NULL,
  type varchar(50) CHECK (type IN ('PURCHASE','PURCHASE_RETURN','EMPTY_RETURN','ADJUSTMENT_ADD','ADJUSTMENT_SUBTRACT','NEW_VALUE','BOOKING_ADD')) NOT NULL,
  quantity integer DEFAULT NULL,
  isApproved boolean NOT NULL DEFAULT false,
  reference_id bigint DEFAULT NULL,
  created_by integer REFERENCES users (id) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  driver_id integer REFERENCES drivers (id) DEFAULT NULL,
  stock_from varchar(50) CHECK (stock_from IN ('depot','godown','driver','default','stock_out')) NOT NULL DEFAULT 'default',
  is_defective boolean NOT NULL DEFAULT false,
  batch_no varchar(50) DEFAULT NULL,
  allocation_sale_id integer DEFAULT NULL,
  allocation_sales_item_id integer DEFAULT NULL
);

CREATE TABLE sales (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  customer_id integer REFERENCES customers (id) ON DELETE CASCADE DEFAULT NULL,
  driver_id integer REFERENCES drivers (id) DEFAULT NULL,
  total_amount decimal(10,2) DEFAULT NULL,
  payment_method varchar(50) CHECK (payment_method IN ('CASH','ONLINE','UPI','PART_PAYMENT')) DEFAULT NULL,
  status varchar(50) CHECK (status IN ('PENDING','ASSIGNED','DELIVERED','CANCELLED')) DEFAULT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  assigned_at timestamp with time zone DEFAULT NULL,
  delivered_at timestamp with time zone DEFAULT NULL,
  address_id integer REFERENCES addresses (id) DEFAULT NULL,
  empty_cylinder_qty integer NOT NULL DEFAULT 0,
  empty_cylinder_status varchar(50) CHECK (empty_cylinder_status IN ('PENDING','DELIVERED','PARTIAL_PENDING','PARTIAL_DELIVERED')) NOT NULL DEFAULT 'PENDING',
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  sale_type varchar(50) CHECK (sale_type IN ('SALE','BOOKING')) NOT NULL DEFAULT 'SALE',
  sales_from varchar(50) CHECK (sales_from IN ('DRIVER','CASHIER')) NOT NULL DEFAULT 'DRIVER'
);

CREATE TABLE sales_items (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  sale_id integer REFERENCES sales (id) ON DELETE CASCADE DEFAULT NULL,
  product_id integer REFERENCES products (id) DEFAULT NULL,
  quantity integer DEFAULT NULL,
  price decimal(10,2) DEFAULT NULL,
  status varchar(50) CHECK (status IN ('PENDING','ASSIGNED','DELIVERED','CANCELLED')) DEFAULT 'ASSIGNED',
  delivered_qty integer DEFAULT 0,
  empty_cylinder_qty integer DEFAULT 0,
  defective_qty integer DEFAULT 0,
  empty_cylinder_status varchar(50) CHECK (empty_cylinder_status IN ('PENDING','DELIVERED','PARTIAL_PENDING','PARTIAL_DELIVERED')) DEFAULT 'PENDING',
  batch_no varchar(50) DEFAULT NULL,
  allocation_sale_id integer DEFAULT NULL,
  allocation_sales_item_id integer DEFAULT NULL
);

CREATE TABLE payments (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  sale_id integer REFERENCES sales (id) ON DELETE CASCADE DEFAULT NULL,
  amount decimal(10,2) DEFAULT NULL,
  method varchar(50) CHECK (method IN ('CASH','UPI','CARD')) DEFAULT NULL,
  status varchar(50) CHECK (status IN ('SUCCESS','PENDING')) DEFAULT 'SUCCESS',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  type varchar(50) CHECK (type IN ('DRIVER','COMPANY')) DEFAULT 'DRIVER'
);

CREATE TABLE settlement_history (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  driver_id integer NOT NULL REFERENCES drivers (id),
  sale_id integer NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
  payment_id integer NOT NULL REFERENCES payments (id) ON DELETE CASCADE,
  method varchar(50) CHECK (method IN ('CASH','UPI')) NOT NULL,
  amount decimal(10,2) NOT NULL,
  status varchar(50) CHECK (status IN ('PENDING','SETTLED','ASSIGNED')) NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cashier_closings (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  total_cash decimal(12,2) NOT NULL DEFAULT 0.00,
  petty_cash decimal(12,2) NOT NULL DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_otp_logs (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  agency_id integer NOT NULL REFERENCES agencies (id) ON DELETE CASCADE,
  user_id integer REFERENCES users (id) ON DELETE SET NULL DEFAULT NULL,
  identifier varchar(120) NOT NULL,
  otp varchar(10) NOT NULL,
  stage varchar(50) CHECK (stage IN ('REQUEST','VERIFY')) NOT NULL DEFAULT 'VERIFY',
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Seed Initial Agency
INSERT INTO agencies (name, contact_email, phone, status)
VALUES ('LPG Digi Default Agency', 'admin@lpgdigi.com', '9000000000', 'ACTIVE');

-- Seed Initial Users (Assigning to Agency ID 1)
INSERT INTO users (agency_id, name, email, phone, password, role, status)
VALUES
  (1, 'Rahul Driver', 'driver1@lpgdigi.com', '9000000001', '$2b$10$1fzRcUx.txHRSoNPPqH7ceJl/o5rGCsepjsir1YH9Vm54.dPVb4p2', 'DRIVER', 'ACTIVE'),
  (1, 'Meena Godown', 'godown1@lpgdigi.com', '9000000002', '$2b$10$1fzRcUx.txHRSoNPPqH7ceJl/o5rGCsepjsir1YH9Vm54.dPVb4p2', 'GODOWN_MANAGER', 'ACTIVE'),
  (1, 'Arun Purchase', 'purchase1@lpgdigi.com', '9000000003', '$2b$10$1fzRcUx.txHRSoNPPqH7ceJl/o5rGCsepjsir1YH9Vm54.dPVb4p2', 'PURCHASE_MANAGER', 'ACTIVE'),
  (1, 'Kiran Cashier', 'cashier1@lpgdigi.com', '9000000004', '$2b$10$1fzRcUx.txHRSoNPPqH7ceJl/o5rGCsepjsir1YH9Vm54.dPVb4p2', 'CASHIER', 'ACTIVE');

-- --------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) FOR MULTI-TENANCY
-- --------------------------------------------------------

-- 1. Helper function to read agency_id from Node.js backend session
CREATE OR REPLACE FUNCTION get_current_agency_id() RETURNS integer AS $$
  SELECT NULLIF(current_setting('app.current_agency_id', true), '')::integer;
$$ LANGUAGE sql STABLE;

-- 2. Enable RLS on all operational tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_job_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_loads ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_load_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE settlement_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE cashier_closings ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_otp_logs ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies for Agency Isolation
-- This forces every query to only return or modify rows where the agency_id matches the active session.

CREATE POLICY "Agency Isolation Policy" ON users FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON user_job_profiles FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON categories FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON stock_areas FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON drivers FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON addresses FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON expenses FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON purchase_trips FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON purchase_loads FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON products FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON customers FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON purchase_load_items FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON reports FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON issues FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON cash_collections FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON settlements FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON stock FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON stock_transactions FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON sales FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON sales_items FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON payments FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON settlement_history FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON cashier_closings FOR ALL USING (agency_id = get_current_agency_id());
CREATE POLICY "Agency Isolation Policy" ON auth_otp_logs FOR ALL USING (agency_id = get_current_agency_id());
